bdd-init:
    number-of-files: 3

    file1:
        path: ../Resources/datas/import-tags.csv
        entities:
          Tag:
            fields: 2
              field:
                name: string
                description: string

    file2:
        path: ../Resources/datas/import-softwares.csv
        entities:
          SoftMain:
            fields: 6
                name: string
                type: string
                description: string
                comments: string
                advantages: string
                drawbacks: string

          SoftInfo:
            fields: 6
              field:
                SoftOutbound: booleen
                SoftCommSupport: booleen
                SoftLeadsOperation: booleen
                SoftSegmentOperation: booleen
                SoftMarketingCampaign: booleen
                SoftSocialMedia: booleen
                SoftReport: booleen
                SoftSupport: booleen
                SoftOtherFunctionnalities: booleen
            Links:
              Target: SoftMain
              Relation: One-to-One
          SoftInfo:
            fields: 9
              field:
                rgpd: booleen
                customers: booleen
                hostingCountry: booleen
                creationDate: booleen
                annualTurnover: booleen
                configCost: booleen
                subscriptionCost: booleen
                trainingCost: booleen
                webSite: booleen
            Links:
              Target: SoftMain
              Relation: One-to-One

          SoftOutbound:
            fields: 7
              field:
                isEmail: booleen
                isSms: booleen
                isPopin: booleen
                isMailPostal: booleen
                isCallCenter: booleen
                isPushMobile: booleen
                isApi: booleen
            Links:
              Target: SoftMain
              Relation: One-to-One

          SoftCommSupport:
            fields: 4
              field:
                isLandingPage: booleen
                isForm: booleen
                isTracking: booleen
                isLiveChat: booleen
            Links:
              Target: SoftMain
              Relation: One-to-One

          SoftLeadsOperation:
            fields: 7
              field:
                isContactObject: booleen
                isCompanyObject: booleen
                isDefinedFields: booleen
                isIllimitedFields: booleen
                isImportCsv: booleen
                isAutoDuplicate: booleen
                isLeadStages: booleen
            Links:
              Target: SoftMain
              Relation: One-to-One

          SoftSegmentOperation:
            fields: 2
              field:
                isSegmentCreation: booleen
                isIntelligentSegment: booleen
            Links:
              Target: SoftMain
              Relation: One-to-One

          SoftMarketingCampaign:
            fields: 4
              field:
                isLeadScoring: booleen
                isCreationCampaign: booleen
                isDripMarketingCampaign: booleen
                isDragAndDrop: booleen
            Links:
              Target: SoftMain
              Relation: One-to-One

          SoftSocialMedia:
            fields: 8
              field:
                isTwitterMonitoring: booleen
                isTwitterAutoPublication: booleen
                isFacebookMonitoring: booleen
                isFacebookAutoPublication: booleen
                isLinkedinMonitoring: booleen
                isLinkedinAutoPublication: booleen
                isInstagramMonitoring: booleen
                isInstagramAutoPublication: booleen
            Links:
              Target: SoftMain
              Relation: One-to-One

          SoftReport:
            fields: 2
              field:
                isActivityReportCreation: booleen
                isActivityReportPeriodicSend: booleen
            Links:
              Target: SoftMain
              Relation: One-to-One

          SoftSupport:
            fields: 6
              field:
                isEmailSupport: booleen
                isPhoneSupport: booleen
                isChatSupport: booleen
                isKnowledgeBase: booleen
                knowledgeBaseLanguage: booleen
                isTechnicalDocument: booleen
            Links:
              Target: SoftMain
              Relation: One-to-One

          SoftOtherFunctionnalities:
            fields: 5
              field:
                isProviderEmailChoice: booleen
                isBlogEdition: booleen
                isTouchPad: booleen
                isSmtpRelay: booleen
                isRssToEmail: booleen
            Links:
              Target: SoftMain
              Relation: One-to-One

    file3:
        path: ../Resources/datas/import-versus.csv
        entities:
          Versus:
            fields: 3
              field:
                software1: string
                software2: string
                description: string
            Links:
              Target: SoftMain
              Relation: Many-to-Many