number-of-files: 3
file1:
    path: ../Resources/datas/import-tags.csv
    entities:
      Tag:
        fields:
          name: string
          description: string
        links:
          source: ??
          relation: ??
        slugExceptions:
          slug: yes
          logo: no


file2:
        path: ../Resources/datas/import-softwares.csv
        entities:
          SoftMain:
            fields:
                name: string
                type: string
                description: string
                comments: string
                advantages: string
                drawbacks: string
            links:
              source: no
              relation: no
            slugExceptions:
              slug: yes
              logo: yes

          SoftInfo:
            fields:
                rgpd: booleen
                customers: booleen
                hostingCountry: booleen
                creationDate: booleen
                annualTurnover: booleen
                configCost: booleen
                subscriptionCost: booleen
                trainingCost: booleen
                webSite: booleen
            links:
              source: SoftMain
              relation: One-to-One
            slugExceptions:
              slug: no
              logo: no

          SoftOutbound:
            fields:
                isEmail: booleen
                isSms: booleen
                isPopin: booleen
                isMailPostal: booleen
                isCallCenter: booleen
                isPushMobile: booleen
                isApi: booleen
            links:
              source: SoftMain
              relation: One-to-One
            slugExceptions:
            slug: no
            logo: no

          SoftCommSupport:
            fields:
                isLandingPage: booleen
                isForm: booleen
                isTracking: booleen
                isLiveChat: booleen
            links:
              source: SoftMain
              relation: One-to-One
            slugExceptions:
              slug: no
              logo: no

          SoftLeadsOperation:
            fields:
                isContactObject: booleen
                isCompanyObject: booleen
                isDefinedFields: booleen
                isIllimitedFields: booleen
                isImportCsv: booleen
                isAutoDuplicate: booleen
                isLeadStages: booleen
            links:
              source: SoftMain
              relation: One-to-One
            slugExceptions:
              slug: no
              logo: no

          SoftSegmentOperation:
            fields:
                isSegmentCreation: booleen
                isIntelligentSegment: booleen
            links:
              source: SoftMain
              relation: One-to-One
            slugExceptions:
              slug: no
              logo: no

          SoftMarketingCampaign:
            fields:
                isLeadScoring: booleen
                isCreationCampaign: booleen
                isDripMarketingCampaign: booleen
                isDragAndDrop: booleen
            links:
              source: SoftMain
              relation: One-to-One
            slugExceptions:
              slug: no
              logo: no

          SoftSocialMedia:
            fields:
                isTwitterMonitoring: booleen
                isTwitterAutoPublication: booleen
                isFacebookMonitoring: booleen
                isFacebookAutoPublication: booleen
                isLinkedinMonitoring: booleen
                isLinkedinAutoPublication: booleen
                isInstagramMonitoring: booleen
                isInstagramAutoPublication: booleen
            links:
              source: SoftMain
              relation: One-to-One
            slugExceptions:
              slug: no
              logo: no

          SoftReport:
            fields:
                isActivityReportCreation: booleen
                isActivityReportPeriodicSend: booleen
            links:
              source: SoftMain
              relation: One-to-One
            slugExceptions:
              slug: no
              logo: no

          SoftSupport:
            fields:
                isEmailSupport: booleen
                isPhoneSupport: booleen
                isChatSupport: booleen
                isKnowledgeBase: booleen
                knowledgeBaseLanguage: booleen
                isTechnicalDocument: booleen
            links:
              source: SoftMain
              relation: One-to-One
            slugExceptions:
              slug: no
              logo: no

          SoftOtherFunctionnalities:
            fields:
                isProviderEmailChoice: booleen
                isBlogEdition: booleen
                isTouchPad: booleen
                isSmtpRelay: booleen
                isRssToEmail: booleen
            links:
              source: SoftMain
              relation: One-to-One
            slugExceptions:
              slug: no
              logo: no

file3:
        path: ../Resources/datas/import-versus.csv
        entities:
          Versus:
            fields:
                software1: string
                software2: string
                description: string
            Links:
              source: SoftMain
              relation: Many-to-Many
            slugExceptions:
              slug: no
              logo: no

# Gives an array like that :

# "file1" => array:3 [▼
#     "path" => "../Resources/datas/import-tags.csv"
#     "entities" => array:1 [▼
#       "Tag" => null
#     ]
#     "fields" => array:2 [▼
#       "name" => "string"
#       "description" => "string"
#     ]
#   ]